apiVersion: v1
kind: Service
metadata:
  name: geoquery
  namespace: {{ .Release.Namespace }}
  labels:
    app: geoquery
spec:
  type: ClusterIP
  selector:
    app: geoquery-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: metrics
      port: 9090
      targetPort: 9090
