apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoquery-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: geoquery-frontend
  template:
    metadata:
      labels:
        app: geoquery-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: django
          image: {{ .Values.frontend.image }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "3500Mi"
              cpu: "500m"
            limits:
              memory: "4000Mi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /health/ready/
              port: 3000
              httpHeaders:
                - name: Host
                  value: localhost
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 12
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          ports:
            - name: http
              containerPort: 3000
            - name: metrics
              containerPort: 9090
      volumes:
        - name: tmp
          emptyDir: {}
