apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.tasks.background.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: geoquery-background-worker
  template:
    metadata:
      labels:
        app: geoquery-background-worker
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: celery-worker
          image: {{ .Values.backend.image }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          command: ["/app/.venv/bin/celery"]
          args:
            - "-A"
            - "geoquery"
            - "worker"
            - "--loglevel=info"
            - "-Q"
            - "background"
            - "--max-tasks-per-child=100"
          env:
            - name: DJANGO_TIME_ZONE
              value: {{ .Values.django.timeZone }}
            - name: DJANGO_SECRET_KEY
              value: {{ .Values.django.secretKey }}
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ .Values.django.allowedHosts }}
            - name: DJANGO_DEBUG
              value: "{{ .Values.django.debug }}"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: geoquery-db-app
                  key: host
            - name: PG_DBNAME
              valueFrom:
                secretKeyRef:
                  name: geoquery-db-app
                  key: dbname
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: geoquery-db-app
                  key: port
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: geoquery-db-app
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geoquery-db-app
                  key: password
            - name: PROTOMAPS_API_KEY
              value: {{ .Values.protomaps.key }}
            - name: RABBITMQ_HOST
              value: "geoquery-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: geoquery-rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geoquery-rabbitmq-default-user
                  key: password
            - name: CELERY_BROKER_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)//"
