apiVersion: v1
kind: Secret
metadata:
  name: geoquery-redis-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.redis.password | quote }}
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: geoquery-redis
  namespace: {{ .Release.Namespace }}
spec:
  kubernetesConfig:
    image: {{ .Values.redis.image }}
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: geoquery-redis-secret
      key: password
    resources:
      requests:
        cpu: {{ .Values.redis.resources.requests.cpu }}
        memory: {{ .Values.redis.resources.requests.memory }}
      limits:
        cpu: {{ .Values.redis.resources.limits.cpu }}
        memory: {{ .Values.redis.resources.limits.memory }}
